export const REGISTER_DONE = 'REGISTER_DONE'
export const SET_ERRORS = 'SET_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

// @PROFILE_ACTIONS
export const PROFILE = {
  CURRENT: 'GET_PROFILE',
  ALL: 'GET_PROFILES',
  LOADING: 'PROFILE_LOADING',
  NOT_FOUND: 'PROFILE_NOT_FOUND',
  CLEAR: 'CLEAR_CURRENT_PROFILE'
}